// Class: ReadRuleFit
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : RuleFit::RuleFit
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/18       [336402]
Creator        : uh234
Date           : Fri Apr  4 12:32:58 2014
Host           : Linux lxbuild175.cern.ch 2.6.18-308.4.1.el5 #1 SMP Wed Apr 18 16:26:27 CEST 2012 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /export/home/uh234/home/HiggsResearch/test3/AB_new
Training events: 22798
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "True" [Print method-specific help message]
GDTau: "-1.000000e+00" [Gradient-directed (GD) path: default fit cut-off]
GDTauPrec: "1.000000e-02" [GD path: precision of tau]
GDStep: "1.000000e-02" [GD path: step size]
GDNSteps: "10000" [GD path: number of steps]
GDErrScale: "1.020000e+00" [Stop scan when error > scale*errmin]
fEventsMin: "1.000000e-02" [Minimum fraction of events in a splittable node]
fEventsMax: "5.000000e-01" [Maximum fraction of events in a splittable node]
nTrees: "20" [Number of trees in forest.]
RuleMinDist: "1.000000e-03" [Minimum distance between rules]
MinImp: "1.000000e-03" [Minimum rule importance accepted]
Model: "modrulelinear" [Model to be used]
RuleFitModule: "rftmva" [Which RuleFit module to use]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
LinQuantile: "2.500000e-02" [Quantile of linear terms (removes outliers)]
GDPathEveFrac: "5.000000e-01" [Fraction of events used for the path search]
GDValidEveFrac: "5.000000e-01" [Fraction of events used for the validation]
ForestType: "adaboost" [Method to use for forest generation (AdaBoost or RandomForest)]
RFWorkDir: "./rulefit" [Friedman's RuleFit module (RFF): working dir]
RFNrules: "2000" [RFF: Mximum number of rules]
RFNendnodes: "4" [RFF: Average number of end nodes]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 5
cth1                          cth1                          cth1                          Variable 1                    units                             'F'    [-0.999111533165,0.999901413918]
cth2                          cth2                          cth2                          Variable 2                    units                             'F'    [-0.999842405319,0.999910354614]
phi                           phi                           phi                           Variable 3                    units                             'F'    [-3.1415014267,3.14156246185]
m12                           m12                           m12                           Variable 4                    units                             'F'    [2.28118228912,105.415939331]
m34                           m34                           m34                           Variable 5                    units                             'F'    [0.437031298876,88.3182373047]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadRuleFit : public IClassifierReader {

 public:

   // constructor
   ReadRuleFit( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadRuleFit" ),
        fNvars( 5 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "cth1", "cth2", "phi", "m12", "m34" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadRuleFit() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[5];
   double fVmax[5];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[5];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   // not implemented for class: "ReadRuleFit"
};
void   ReadRuleFit::Initialize(){}
void   ReadRuleFit::Clear(){}
double ReadRuleFit::GetMvaValue__( const std::vector<double>& inputValues ) const {
   double rval=-0.0005710572206;
   //
   // here follows all rules ordered in importance (most important first)
   // at the end of each line, the relative importance of the rule is given
   //
   if ((inputValues[0]<0.3335637748)&&(-0.747947216<inputValues[2])) rval+=0.1065799774;   // importance = 0.529
   if ((0.5239389539<inputValues[1])&&(-2.543114424<inputValues[2])) rval+=-0.1012179417;   // importance = 0.464
   if ((inputValues[1]<0.8094577193)&&(inputValues[3]<51.39297104)) rval+=0.1373643902;   // importance = 0.420
   if ((inputValues[0]<0.4286483228)&&(-1.090400577<inputValues[2])&&(inputValues[2]<0.4488207996)) rval+=0.09600933609;   // importance = 0.366
   if ((0.2383479923<inputValues[0])&&(48.11862946<inputValues[3])&&(17.17630959<inputValues[4])) rval+=-0.07425548925;   // importance = 0.358
   if ((0.5237787366<inputValues[1])&&(59.73098755<inputValues[3])) rval+=-0.07806969498;   // importance = 0.348
   if ((0.8094577193<inputValues[1])) rval+=-0.09982967577;   // importance = 0.338
   if ((inputValues[0]<0.7139629722)&&(inputValues[1]<0.8094577193)&&(inputValues[2]<-2.243912458)&&(51.39297104<inputValues[3])) rval+=0.1035637675;   // importance = 0.308
   if ((85.77122498<inputValues[3])&&(25.54594803<inputValues[4])) rval+=0.06208787187;   // importance = 0.281
   if ((inputValues[1]<0.5239389539)&&(-2.543114424<inputValues[2])) rval+=0.04136276331;   // importance = 0.203
   if ((41.57061386<inputValues[3])&&(inputValues[3]<79.35881805)&&(14.66323853<inputValues[4])) rval+=-0.02796163397;   // importance = 0.132
   if ((17.17630959<inputValues[4])) rval+=-0.03575672281;   // importance = 0.111
   if ((inputValues[0]<0.4286483228)&&(inputValues[2]<0.4488207996)) rval+=0.02087835496;   // importance = 0.104
   if ((inputValues[2]<1.645594835)&&(41.57061386<inputValues[3])&&(inputValues[3]<79.35881805)&&(14.66323853<inputValues[4])) rval+=-0.01719164823;   // importance = 0.074
   if ((inputValues[0]<0.2383479923)&&(48.11862946<inputValues[3])&&(17.17630959<inputValues[4])) rval+=-0.01306648909;   // importance = 0.066
   if ((-0.3490577638<inputValues[2])&&(inputValues[2]<1.047207832)) rval+=0.01289849292;   // importance = 0.054
   if ((inputValues[1]<0.5237787366)&&(83.66841125<inputValues[3])) rval+=0.00908025542;   // importance = 0.045
   if ((0.5237022042<inputValues[1])&&(-2.543114424<inputValues[2])&&(inputValues[2]<0.8856999278)) rval+=-0.009947445862;   // importance = 0.038
   if ((85.77122498<inputValues[3])&&(inputValues[4]<25.54594803)) rval+=-0.00720546774;   // importance = 0.032
   if ((inputValues[0]<0.7139629722)&&(inputValues[1]<0.8094577193)&&(51.39297104<inputValues[3])) rval+=0.0007751620223;   // importance = 0.004
   //
   // here follows all linear terms
   // at the end of each line, the relative importance of the term is given
   //
   rval+=-0.008607769621*std::min( double(0.9622211456), std::max( double(inputValues[1]), double(-0.5685395002)));   // importance = 0.037
   rval+=0.003904946298*std::min( double(93.64753723), std::max( double(inputValues[3]), double(33.98164368)));   // importance = 0.644
   rval+=-0.007178842526*std::min( double(70.82280731), std::max( double(inputValues[4]), double(9.456549644)));   // importance = 1.000
   return rval;
}
   inline double ReadRuleFit::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
