// Class: ReadRuleFit
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : RuleFit::RuleFit
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/18       [336402]
Creator        : uh234
Date           : Sat Apr  5 13:50:25 2014
Host           : Linux lxbuild175.cern.ch 2.6.18-308.4.1.el5 #1 SMP Wed Apr 18 16:26:27 CEST 2012 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /export/home/uh234/home/HiggsResearch/test3/AB_1
Training events: 14148
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "True" [Print method-specific help message]
GDTau: "-1.000000e+00" [Gradient-directed (GD) path: default fit cut-off]
GDTauPrec: "1.000000e-02" [GD path: precision of tau]
GDStep: "1.000000e-02" [GD path: step size]
GDNSteps: "10000" [GD path: number of steps]
GDErrScale: "1.020000e+00" [Stop scan when error > scale*errmin]
fEventsMin: "1.000000e-02" [Minimum fraction of events in a splittable node]
fEventsMax: "5.000000e-01" [Maximum fraction of events in a splittable node]
nTrees: "20" [Number of trees in forest.]
RuleMinDist: "1.000000e-03" [Minimum distance between rules]
MinImp: "1.000000e-03" [Minimum rule importance accepted]
Model: "modrulelinear" [Model to be used]
RuleFitModule: "rftmva" [Which RuleFit module to use]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
LinQuantile: "2.500000e-02" [Quantile of linear terms (removes outliers)]
GDPathEveFrac: "5.000000e-01" [Fraction of events used for the path search]
GDValidEveFrac: "5.000000e-01" [Fraction of events used for the validation]
ForestType: "adaboost" [Method to use for forest generation (AdaBoost or RandomForest)]
RFWorkDir: "./rulefit" [Friedman's RuleFit module (RFF): working dir]
RFNrules: "2000" [RFF: Mximum number of rules]
RFNendnodes: "4" [RFF: Average number of end nodes]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 5
cth1                          cth1                          cth1                          Variable 1                    units                             'F'    [-0.999111533165,0.999475419521]
cth2                          cth2                          cth2                          Variable 2                    units                             'F'    [-0.999997198582,0.999910354614]
phi                           phi                           phi                           Variable 3                    units                             'F'    [-3.14149165154,3.1407725811]
m12                           m12                           m12                           Variable 4                    units                             'F'    [2.26048517227,101.096740723]
m34                           m34                           m34                           Variable 5                    units                             'F'    [0.437031298876,88.0874557495]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadRuleFit : public IClassifierReader {

 public:

   // constructor
   ReadRuleFit( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadRuleFit" ),
        fNvars( 5 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "cth1", "cth2", "phi", "m12", "m34" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadRuleFit() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[5];
   double fVmax[5];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[5];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   // not implemented for class: "ReadRuleFit"
};
void   ReadRuleFit::Initialize(){}
void   ReadRuleFit::Clear(){}
double ReadRuleFit::GetMvaValue__( const std::vector<double>& inputValues ) const {
   double rval=0.05742325377;
   //
   // here follows all rules ordered in importance (most important first)
   // at the end of each line, the relative importance of the rule is given
   //
   if ((-0.4280866981<inputValues[0])&&(inputValues[1]<0.5237419009)) rval+=0.416871009;   // importance = 1.000
   if ((inputValues[3]<86.97727203)) rval+=-0.3489849113;   // importance = 0.879
   if ((inputValues[0]<0.5235452652)&&(inputValues[1]<0.809442997)&&(17.34390068<inputValues[4])) rval+=0.3422013946;   // importance = 0.840
   if ((inputValues[3]<86.58560181)&&(28.25554657<inputValues[4])) rval+=-0.3425303496;   // importance = 0.839
   if ((inputValues[0]<0.5235452652)&&(inputValues[1]<0.809442997)&&(inputValues[2]<2.24330616)&&(17.34390068<inputValues[4])) rval+=-0.2416778262;   // importance = 0.609
   if ((-1.645714402<inputValues[2])&&(inputValues[3]<86.97727203)) rval+=-0.2414222339;   // importance = 0.585
   if ((-1.645714402<inputValues[2])&&(86.97727203<inputValues[3])) rval+=-0.2248713161;   // importance = 0.558
   if ((inputValues[0]<0.3332797587)) rval+=0.2165520884;   // importance = 0.522
   if ((inputValues[2]<0.1541886777)&&(inputValues[3]<91.6837616)) rval+=-0.1953713759;   // importance = 0.490
   if ((inputValues[1]<0.3332745135)&&(inputValues[3]<82.32945251)) rval+=-0.1839427778;   // importance = 0.403
   if ((-0.8095298409<inputValues[1])&&(inputValues[1]<0.5379186869)&&(25.48000908<inputValues[4])) rval+=-0.1156516709;   // importance = 0.290
   if ((inputValues[1]<0.3332745135)&&(82.32945251<inputValues[3])) rval+=-0.1147774468;   // importance = 0.284
   if ((-2.543180704<inputValues[2])&&(66.13401794<inputValues[3])&&(inputValues[4]<32.65704346)) rval+=-0.1077318181;   // importance = 0.271
   if ((-0.8095298409<inputValues[1])&&(inputValues[3]<91.00465393)) rval+=0.1100854265;   // importance = 0.254
   if ((inputValues[1]<0.4285081923)&&(inputValues[2]<0.7475290895)) rval+=0.08965530918;   // importance = 0.224
   if ((-0.8095298409<inputValues[1])) rval+=0.1454415373;   // importance = 0.211
   if ((0.3332797587<inputValues[0])) rval+=-0.0792708089;   // importance = 0.191
   if ((inputValues[1]<0.3332745135)&&(-1.090991378<inputValues[2])) rval+=0.07066563096;   // importance = 0.177
   if ((inputValues[0]<0.3332797587)&&(-1.346559048<inputValues[2])) rval+=0.06029083963;   // importance = 0.152
   if ((67.66963959<inputValues[3])&&(28.25554657<inputValues[4])) rval+=0.05202795428;   // importance = 0.125
   if ((inputValues[4]<58.87064743)) rval+=-0.07583760309;   // importance = 0.102
   if ((-0.3651309311<inputValues[1])&&(inputValues[1]<0.3332745135)) rval+=0.03978171263;   // importance = 0.096
   if ((0.7475290895<inputValues[2])) rval+=-0.03526550806;   // importance = 0.087
   if ((-0.8095298409<inputValues[1])&&(-0.1519735754<inputValues[2])&&(82.55137634<inputValues[3])) rval+=-0.03425197859;   // importance = 0.078
   if ((86.97727203<inputValues[3])&&(inputValues[4]<23.53520966)) rval+=-0.03509683712;   // importance = 0.072
   if ((0.3766110837<inputValues[2])&&(inputValues[3]<77.48818207)&&(17.13235092<inputValues[4])) rval+=-0.02539351896;   // importance = 0.046
   if ((70.84029388<inputValues[3])&&(inputValues[3]<86.97727203)) rval+=0.01904446879;   // importance = 0.039
   if ((inputValues[0]<0.2381089628)&&(-0.2381276488<inputValues[1])) rval+=0.01247496006;   // importance = 0.030
   if ((inputValues[0]<0.1837529242)&&(-0.2225860804<inputValues[1])&&(inputValues[1]<0.5237419009)) rval+=0.01217224344;   // importance = 0.025
   if ((-0.5495742559<inputValues[2])&&(inputValues[2]<0.7475290895)) rval+=0.009783597732;   // importance = 0.020
   if ((-0.3333613575<inputValues[1])&&(-2.543180704<inputValues[2])&&(66.13401794<inputValues[3])&&(32.65704346<inputValues[4])) rval+=0.009705901451;   // importance = 0.015
   if ((inputValues[2]<1.644995332)) rval+=-0.006834479499;   // importance = 0.015
   if ((-0.8095298409<inputValues[1])&&(inputValues[1]<0.5379186869)&&(inputValues[4]<25.48000908)) rval+=0.006677943057;   // importance = 0.014
   if ((inputValues[0]<0.5235452652)&&(inputValues[1]<0.809442997)&&(0.9597398639<inputValues[2])&&(17.34390068<inputValues[4])) rval+=-0.005784080727;   // importance = 0.012
   if ((58.87064743<inputValues[4])) rval+=0.008409290247;   // importance = 0.011
   if ((-0.8095298409<inputValues[1])&&(inputValues[2]<-0.1519735754)&&(82.55137634<inputValues[3])) rval+=-0.004474139083;   // importance = 0.010
   if ((inputValues[3]<86.97727203)&&(inputValues[4]<33.82767105)) rval+=0.003049329773;   // importance = 0.006
   if ((inputValues[0]<0.5235452652)&&(inputValues[1]<0.809442997)&&(inputValues[4]<17.34390068)) rval+=0.002742894788;   // importance = 0.004
   if ((inputValues[0]<0.5235452652)&&(inputValues[1]<0.809442997)&&(-2.360514879<inputValues[2])&&(inputValues[2]<0.9597398639)&&(17.34390068<inputValues[4])&&(inputValues[4]<27.47451019)) rval+=-0.002411793768;   // importance = 0.004
   if ((-0.8095298409<inputValues[1])&&(inputValues[1]<0.5379186869)&&(inputValues[2]<0.4484756887)&&(inputValues[4]<25.48000908)) rval+=0.001950109944;   // importance = 0.003
   if ((-0.2516053915<inputValues[0])&&(inputValues[0]<0.04776734859)) rval+=0.001216424482;   // importance = 0.002
   if ((-0.8095298409<inputValues[1])&&(91.00465393<inputValues[3])) rval+=0.001085299319;   // importance = 0.002
   //
   // here follows all linear terms
   // at the end of each line, the relative importance of the term is given
   //
   rval+=-0.00211558035*std::min( double(93.57501984), std::max( double(inputValues[3]), double(35.37728119)));   // importance = 0.174
   rval+=-0.001765528781*std::min( double(70.91698456), std::max( double(inputValues[4]), double(9.308494568)));   // importance = 0.127
   return rval;
}
   inline double ReadRuleFit::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
